version: '3.9'

services:
    database_service:
        image: postgres
        restart: always
        ports:
            - "9091:5432"
        environment:
            - POSTGRES_DB=weblib_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
