spring:
  application:
    name: backend
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      exclude: src/main/resources/static/userImages
      additional-exclude: src/main/resources/static/images

server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true